
export const DUMMY_ARR_FAVORITE = [
    {
        "login": "fabpot",
        "id": 47313,
        "node_id": "MDQ6VXNlcjQ3MzEz",
        "avatar_url": "https://avatars.githubusercontent.com/u/47313?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fabpot",
        "html_url": "https://github.com/fabpot",
        "followers_url": "https://api.github.com/users/fabpot/followers",
        "following_url": "https://api.github.com/users/fabpot/following{/other_user}",
        "gists_url": "https://api.github.com/users/fabpot/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/fabpot/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/fabpot/subscriptions",
        "organizations_url": "https://api.github.com/users/fabpot/orgs",
        "repos_url": "https://api.github.com/users/fabpot/repos",
        "events_url": "https://api.github.com/users/fabpot/events{/privacy}",
        "received_events_url": "https://api.github.com/users/fabpot/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Fabien Potencier",
        "company": "Symfony/Platform.sh/Blackfire",
        "blog": "http://fabien.potencier.org/",
        "location": "Lille, France",
        "email": null,
        "hireable": null,
        "bio": "CEO at Symfony, CPO at Platform.sh\r\n",
        "twitter_username": "fabpot",
        "public_repos": 69,
        "public_gists": 12,
        "followers": 12415,
        "following": 0,
        "created_at": "2009-01-17T13:42:51Z",
        "updated_at": "2022-07-01T06:13:15Z"
      },
      {
        "login": "andrew",
        "id": 1060,
        "node_id": "MDQ6VXNlcjEwNjA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1060?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/andrew",
        "html_url": "https://github.com/andrew",
        "followers_url": "https://api.github.com/users/andrew/followers",
        "following_url": "https://api.github.com/users/andrew/following{/other_user}",
        "gists_url": "https://api.github.com/users/andrew/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/andrew/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/andrew/subscriptions",
        "organizations_url": "https://api.github.com/users/andrew/orgs",
        "repos_url": "https://api.github.com/users/andrew/repos",
        "events_url": "https://api.github.com/users/andrew/events{/privacy}",
        "received_events_url": "https://api.github.com/users/andrew/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Andrew Nesbitt",
        "company": "@ecosyste-ms and @octobox ",
        "blog": "https://nesbitt.io",
        "location": "UK",
        "email": null,
        "hireable": null,
        "bio": "Software engineer and researcher",
        "twitter_username": "teabass",
        "public_repos": 307,
        "public_gists": 193,
        "followers": 3007,
        "following": 3160,
        "created_at": "2008-02-27T11:39:22Z",
        "updated_at": "2022-05-25T09:38:58Z"
      },
      {
        "login": "taylorotwell",
        "id": 463230,
        "node_id": "MDQ6VXNlcjQ2MzIzMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/463230?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/taylorotwell",
        "html_url": "https://github.com/taylorotwell",
        "followers_url": "https://api.github.com/users/taylorotwell/followers",
        "following_url": "https://api.github.com/users/taylorotwell/following{/other_user}",
        "gists_url": "https://api.github.com/users/taylorotwell/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/taylorotwell/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/taylorotwell/subscriptions",
        "organizations_url": "https://api.github.com/users/taylorotwell/orgs",
        "repos_url": "https://api.github.com/users/taylorotwell/repos",
        "events_url": "https://api.github.com/users/taylorotwell/events{/privacy}",
        "received_events_url": "https://api.github.com/users/taylorotwell/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Taylor Otwell",
        "company": "Laravel",
        "blog": "http://laravel.com",
        "location": "Little Rock, AR",
        "email": null,
        "hireable": null,
        "bio": "Creator of @laravel.",
        "twitter_username": null,
        "public_repos": 27,
        "public_gists": 9,
        "followers": 25897,
        "following": 1,
        "created_at": "2010-11-01T20:15:30Z",
        "updated_at": "2022-06-01T13:39:51Z"
      },
      {
        "login": "egoist",
        "id": 8784712,
        "node_id": "MDQ6VXNlcjg3ODQ3MTI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8784712?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/egoist",
        "html_url": "https://github.com/egoist",
        "followers_url": "https://api.github.com/users/egoist/followers",
        "following_url": "https://api.github.com/users/egoist/following{/other_user}",
        "gists_url": "https://api.github.com/users/egoist/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/egoist/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/egoist/subscriptions",
        "organizations_url": "https://api.github.com/users/egoist/orgs",
        "repos_url": "https://api.github.com/users/egoist/repos",
        "events_url": "https://api.github.com/users/egoist/events{/privacy}",
        "received_events_url": "https://api.github.com/users/egoist/received_events",
        "type": "User",
        "site_admin": false,
        "name": "EGOIST",
        "company": "Mom's basement",
        "blog": "https://egoist.sh",
        "location": "China",
        "email": null,
        "hireable": true,
        "bio": "Full-Time Open-Sourcerer. Writing TypeScript most of the time.",
        "twitter_username": "_egoistlily",
        "public_repos": 754,
        "public_gists": 160,
        "followers": 10192,
        "following": 26,
        "created_at": "2014-09-15T22:08:21Z",
        "updated_at": "2022-07-02T06:15:25Z"
      },
{
    "login": "ornicar",
    "id": 140370,
    "node_id": "MDQ6VXNlcjE0MDM3MA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/140370?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ornicar",
    "html_url": "https://github.com/ornicar",
    "followers_url": "https://api.github.com/users/ornicar/followers",
    "following_url": "https://api.github.com/users/ornicar/following{/other_user}",
    "gists_url": "https://api.github.com/users/ornicar/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ornicar/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ornicar/subscriptions",
    "organizations_url": "https://api.github.com/users/ornicar/orgs",
    "repos_url": "https://api.github.com/users/ornicar/repos",
    "events_url": "https://api.github.com/users/ornicar/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ornicar/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Thibault Duplessis",
    "company": "lichess.org",
    "blog": "https://lichess.org",
    "location": "France",
    "email": null,
    "hireable": null,
    "bio": "Maker of lichess.org, a hippie communist chess server for drug fueled atheists.",
    "twitter_username": "ornicar",
    "public_repos": 393,
    "public_gists": 402,
    "followers": 4371,
    "following": 184,
    "created_at": "2009-10-15T20:28:03Z",
    "updated_at": "2022-05-05T06:46:58Z"
  },
  {
    "login": "nelsonic",
    "id": 194400,
    "node_id": "MDQ6VXNlcjE5NDQwMA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/194400?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nelsonic",
    "html_url": "https://github.com/nelsonic",
    "followers_url": "https://api.github.com/users/nelsonic/followers",
    "following_url": "https://api.github.com/users/nelsonic/following{/other_user}",
    "gists_url": "https://api.github.com/users/nelsonic/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nelsonic/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nelsonic/subscriptions",
    "organizations_url": "https://api.github.com/users/nelsonic/orgs",
    "repos_url": "https://api.github.com/users/nelsonic/repos",
    "events_url": "https://api.github.com/users/nelsonic/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nelsonic/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Nelson",
    "company": "@dwyl",
    "blog": "https://dwyl.com",
    "location": "London",
    "email": null,
    "hireable": null,
    "bio": "Love learning/writing code @dwyl \r\nSystematic about sharing all knowledge/skills. Learn something new every day. \r\nhttps://github.com/dwyl/?q=learn",
    "twitter_username": "nelsonic",
    "public_repos": 306,
    "public_gists": 34,
    "followers": 3255,
    "following": 17879,
    "created_at": "2010-02-02T08:44:49Z",
    "updated_at": "2022-07-02T20:01:18Z"
  },
{
        "login": "yegor256",
        "id": 526301,
        "node_id": "MDQ6VXNlcjUyNjMwMQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/526301?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/yegor256",
        "html_url": "https://github.com/yegor256",
        "followers_url": "https://api.github.com/users/yegor256/followers",
        "following_url": "https://api.github.com/users/yegor256/following{/other_user}",
        "gists_url": "https://api.github.com/users/yegor256/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/yegor256/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/yegor256/subscriptions",
        "organizations_url": "https://api.github.com/users/yegor256/orgs",
        "repos_url": "https://api.github.com/users/yegor256/repos",
        "events_url": "https://api.github.com/users/yegor256/events{/privacy}",
        "received_events_url": "https://api.github.com/users/yegor256/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Yegor Bugayenko",
        "company": "@zerocracy",
        "blog": "https://www.yegor256.com",
        "location": null,
        "email": null,
        "hireable": true,
        "bio": "Author of \"Elegant Objects\" book series (buy them on Amazon); founder of @zerocracy; creator of @zold-io",
        "twitter_username": "yegor256",
        "public_repos": 151,
        "public_gists": 6,
        "followers": 4022,
        "following": 4,
        "created_at": "2010-12-16T20:09:39Z",
        "updated_at": "2022-03-02T14:21:46Z"
      },
      {
        "login": "alexcrichton",
        "id": 64996,
        "node_id": "MDQ6VXNlcjY0OTk2",
        "avatar_url": "https://avatars.githubusercontent.com/u/64996?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/alexcrichton",
        "html_url": "https://github.com/alexcrichton",
        "followers_url": "https://api.github.com/users/alexcrichton/followers",
        "following_url": "https://api.github.com/users/alexcrichton/following{/other_user}",
        "gists_url": "https://api.github.com/users/alexcrichton/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/alexcrichton/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/alexcrichton/subscriptions",
        "organizations_url": "https://api.github.com/users/alexcrichton/orgs",
        "repos_url": "https://api.github.com/users/alexcrichton/repos",
        "events_url": "https://api.github.com/users/alexcrichton/events{/privacy}",
        "received_events_url": "https://api.github.com/users/alexcrichton/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Alex Crichton",
        "company": null,
        "blog": "",
        "location": null,
        "email": null,
        "hireable": null,
        "bio": null,
        "twitter_username": null,
        "public_repos": 426,
        "public_gists": 1627,
        "followers": 4095,
        "following": 0,
        "created_at": "2009-03-19T19:31:50Z",
        "updated_at": "2022-06-30T23:28:31Z"
      },{
        "login": "jonathanong",
        "id": 643505,
        "node_id": "MDQ6VXNlcjY0MzUwNQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/643505?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jonathanong",
        "html_url": "https://github.com/jonathanong",
        "followers_url": "https://api.github.com/users/jonathanong/followers",
        "following_url": "https://api.github.com/users/jonathanong/following{/other_user}",
        "gists_url": "https://api.github.com/users/jonathanong/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jonathanong/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jonathanong/subscriptions",
        "organizations_url": "https://api.github.com/users/jonathanong/orgs",
        "repos_url": "https://api.github.com/users/jonathanong/repos",
        "events_url": "https://api.github.com/users/jonathanong/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jonathanong/received_events",
        "type": "User",
        "site_admin": false,
        "name": "jongleberry",
        "company": "@houzz",
        "blog": "https://jongleberry.com",
        "location": "Los Angeles, CA",
        "email": null,
        "hireable": true,
        "bio": "@expressjs @koajs @jshttp @pillarjs ",
        "twitter_username": "jongleberry",
        "public_repos": 59,
        "public_gists": 1,
        "followers": 2180,
        "following": 150,
        "created_at": "2011-02-28T21:36:17Z",
        "updated_at": "2022-06-24T05:46:45Z"
      },{
        "login": "mikermcneil",
        "id": 618009,
        "node_id": "MDQ6VXNlcjYxODAwOQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/618009?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mikermcneil",
        "html_url": "https://github.com/mikermcneil",
        "followers_url": "https://api.github.com/users/mikermcneil/followers",
        "following_url": "https://api.github.com/users/mikermcneil/following{/other_user}",
        "gists_url": "https://api.github.com/users/mikermcneil/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mikermcneil/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mikermcneil/subscriptions",
        "organizations_url": "https://api.github.com/users/mikermcneil/orgs",
        "repos_url": "https://api.github.com/users/mikermcneil/repos",
        "events_url": "https://api.github.com/users/mikermcneil/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mikermcneil/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Mike McNeil",
        "company": "Fleet (@fleetdm)",
        "blog": "linkedin.com/in/mikermcneil",
        "location": "Austin, Texas",
        "email": null,
        "hireable": null,
        "bio": "CEO, Fleet.  Creator & BDFL, sails.js",
        "twitter_username": "mikermcneil",
        "public_repos": 213,
        "public_gists": 229,
        "followers": 2137,
        "following": 256,
        "created_at": "2011-02-14T20:51:12Z",
        "updated_at": "2021-09-28T15:29:54Z"
      },{
        "login": "benbalter",
        "id": 282759,
        "node_id": "MDQ6VXNlcjI4Mjc1OQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/282759?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/benbalter",
        "html_url": "https://github.com/benbalter",
        "followers_url": "https://api.github.com/users/benbalter/followers",
        "following_url": "https://api.github.com/users/benbalter/following{/other_user}",
        "gists_url": "https://api.github.com/users/benbalter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/benbalter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/benbalter/subscriptions",
        "organizations_url": "https://api.github.com/users/benbalter/orgs",
        "repos_url": "https://api.github.com/users/benbalter/repos",
        "events_url": "https://api.github.com/users/benbalter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/benbalter/received_events",
        "type": "User",
        "site_admin": true,
        "name": "Ben Balter",
        "company": "@GitHub",
        "blog": "https://ben.balter.com",
        "location": "Washington, DC",
        "email": null,
        "hireable": null,
        "bio": "Attorney, open source developer, Chief of Staff for Security @GitHub. Previously @GitHub Trust & Safety and @WhiteHouse Presidential Innovation Fellow.",
        "twitter_username": "benbalter",
        "public_repos": 226,
        "public_gists": 60,
        "followers": 10052,
        "following": 145,
        "created_at": "2010-05-20T20:38:33Z",
        "updated_at": "2022-06-23T23:00:09Z"
      },{
        "login": "jxnblk",
        "id": 3451712,
        "node_id": "MDQ6VXNlcjM0NTE3MTI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3451712?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jxnblk",
        "html_url": "https://github.com/jxnblk",
        "followers_url": "https://api.github.com/users/jxnblk/followers",
        "following_url": "https://api.github.com/users/jxnblk/following{/other_user}",
        "gists_url": "https://api.github.com/users/jxnblk/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jxnblk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jxnblk/subscriptions",
        "organizations_url": "https://api.github.com/users/jxnblk/orgs",
        "repos_url": "https://api.github.com/users/jxnblk/repos",
        "events_url": "https://api.github.com/users/jxnblk/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jxnblk/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Brent Jackson",
        "company": "@gatsbyjs ",
        "blog": "https://jxnblk.com",
        "location": "New York City",
        "email": null,
        "hireable": null,
        "bio": "Building @system-ui @styled-system, @rebassjs, MDX Deck",
        "twitter_username": null,
        "public_repos": 288,
        "public_gists": 46,
        "followers": 5515,
        "following": 37,
        "created_at": "2013-02-01T19:24:48Z",
        "updated_at": "2022-06-07T16:15:35Z"
      }
]